name: Update XML Datafeed

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск кадный день в 00:00. Формат можно подсмотреть на crontab.guru
  workflow_dispatch:  # Можно запускать руками

jobs:
  update-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file found"

      - name: Run datafeed script
        run: python main.py  

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Datafeed"
          git push
